# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install --only=production

# Copy the rest of the application to the container
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the command to start the server
CMD [ "npm", "run", "start" ]
